2011-11-16 22:40:08,029 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:40:10,897 [ERROR] django.request: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:45:02,259 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:45:03,143 [ERROR] django.request: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:45:04,079 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:45:04,515 [ERROR] django.request: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:46:16,605 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:46:18,380 [ERROR] django.request: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:47:12,495 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:47:13,899 [ERROR] django.request: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:47:20,680 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:47:21,504 [ERROR] django.request: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:47:22,112 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:47:22,732 [ERROR] django.request: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:47:23,279 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:47:23,902 [ERROR] django.request: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:48:11,778 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:48:12,456 [ERROR] django.request: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:48:49,138 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:48:49,831 [ERROR] django.request: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:49:29,702 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:49:31,143 [ERROR] django.request: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:49:59,752 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:50:00,396 [ERROR] django.request: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:50:05,319 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:50:06,138 [ERROR] django.request: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:51:08,261 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:51:09,076 [ERROR] django.request: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:51:49,472 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:51:50,103 [ERROR] django.request: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:52:07,693 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:52:08,263 [ERROR] django.request: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:52:21,065 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:52:21,670 [ERROR] django.request: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:52:22,847 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:52:23,398 [ERROR] django.request: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 23:08:14,079 [WARNING] django.request: Not Found: /favicon.ico/
2011-11-16 23:08:58,009 [WARNING] django.request: Not Found: /favicon.ico/
2011-11-16 23:10:27,539 [WARNING] django.request: Not Found: /favicon.ico/
2011-11-16 23:10:39,915 [WARNING] django.request: Not Found: /favicon.ico/
2011-11-16 23:14:24,420 [WARNING] django.request: Not Found: /favicon.ico/
2011-11-16 23:14:28,665 [WARNING] django.request: Not Found: /favicon.ico/
2011-11-16 23:14:32,968 [WARNING] django.request: Not Found: /favicon.ico/
2011-11-16 23:14:51,802 [WARNING] django.request: Not Found: /favicon.ico/
2011-11-16 23:16:13,362 [WARNING] django.request: Not Found: /favicon.ico/
2011-11-16 23:16:18,717 [WARNING] django.request: Not Found: /favicon.ico/
2011-11-16 23:16:48,884 [WARNING] django.request: Not Found: /favicon.ico/
2011-11-16 23:16:52,606 [WARNING] django.request: Not Found: /favicon.ico/
2011-11-16 23:16:54,785 [WARNING] django.request: Not Found: /favicon.ico/
2011-11-17 01:45:54,197 [WARNING] django.request: Not Found: /
2011-11-17 01:45:54,198 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/core/handlers/base.py", line 149, in get_response
    callback, param_dict = resolver.resolve404()
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/core/urlresolvers.py", line 300, in resolve404
    return self._resolve_special('404')
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/core/urlresolvers.py", line 297, in _resolve_special
    raise ViewDoesNotExist("Tried %s. Error was: %s" % (callback, str(e)))
ViewDoesNotExist: Tried nerdfiles_net_dev.views.error_404. Error was: No module named nerdfiles_net_dev.views
2011-11-17 01:45:55,774 [WARNING] django.request: Not Found: /favicon.ico/
2011-11-17 01:45:55,774 [ERROR] django.request: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/core/handlers/base.py", line 149, in get_response
    callback, param_dict = resolver.resolve404()
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/core/urlresolvers.py", line 300, in resolve404
    return self._resolve_special('404')
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/core/urlresolvers.py", line 297, in _resolve_special
    raise ViewDoesNotExist("Tried %s. Error was: %s" % (callback, str(e)))
ViewDoesNotExist: Tried nerdfiles_net_dev.views.error_404. Error was: No module named nerdfiles_net_dev.views
2011-11-17 01:49:23,875 [WARNING] django.request: Not Found: /
2011-11-17 01:49:23,875 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/core/handlers/base.py", line 149, in get_response
    callback, param_dict = resolver.resolve404()
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/core/urlresolvers.py", line 300, in resolve404
    return self._resolve_special('404')
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/core/urlresolvers.py", line 297, in _resolve_special
    raise ViewDoesNotExist("Tried %s. Error was: %s" % (callback, str(e)))
ViewDoesNotExist: Tried nerdfiles_net_dev.views.error_404. Error was: No module named nerdfiles_net_dev.views
2011-11-17 01:49:24,915 [WARNING] django.request: Not Found: /favicon.ico/
2011-11-17 01:49:24,915 [ERROR] django.request: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/core/handlers/base.py", line 149, in get_response
    callback, param_dict = resolver.resolve404()
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/core/urlresolvers.py", line 300, in resolve404
    return self._resolve_special('404')
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/core/urlresolvers.py", line 297, in _resolve_special
    raise ViewDoesNotExist("Tried %s. Error was: %s" % (callback, str(e)))
ViewDoesNotExist: Tried nerdfiles_net_dev.views.error_404. Error was: No module named nerdfiles_net_dev.views
2011-11-17 01:50:31,388 [WARNING] django.request: Not Found: /
2011-11-17 01:50:31,388 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/core/handlers/base.py", line 149, in get_response
    callback, param_dict = resolver.resolve404()
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/core/urlresolvers.py", line 300, in resolve404
    return self._resolve_special('404')
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/core/urlresolvers.py", line 297, in _resolve_special
    raise ViewDoesNotExist("Tried %s. Error was: %s" % (callback, str(e)))
ViewDoesNotExist: Tried nerdfiles_net_dev.views.error_404. Error was: No module named nerdfiles_net_dev.views
2011-11-17 01:50:33,586 [WARNING] django.request: Not Found: /favicon.ico/
2011-11-17 01:50:33,586 [ERROR] django.request: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/core/handlers/base.py", line 149, in get_response
    callback, param_dict = resolver.resolve404()
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/core/urlresolvers.py", line 300, in resolve404
    return self._resolve_special('404')
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/core/urlresolvers.py", line 297, in _resolve_special
    raise ViewDoesNotExist("Tried %s. Error was: %s" % (callback, str(e)))
ViewDoesNotExist: Tried nerdfiles_net_dev.views.error_404. Error was: No module named nerdfiles_net_dev.views
2011-11-17 01:54:13,648 [WARNING] django.request: Not Found: /
2011-11-17 01:54:13,649 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/core/handlers/base.py", line 149, in get_response
    callback, param_dict = resolver.resolve404()
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/core/urlresolvers.py", line 300, in resolve404
    return self._resolve_special('404')
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/core/urlresolvers.py", line 297, in _resolve_special
    raise ViewDoesNotExist("Tried %s. Error was: %s" % (callback, str(e)))
ViewDoesNotExist: Tried nerdfiles_net_dev.views.error_404. Error was: No module named nerdfiles_net_dev.views
2011-11-17 01:54:14,524 [WARNING] django.request: Not Found: /favicon.ico/
2011-11-17 01:54:14,525 [ERROR] django.request: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/core/handlers/base.py", line 149, in get_response
    callback, param_dict = resolver.resolve404()
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/core/urlresolvers.py", line 300, in resolve404
    return self._resolve_special('404')
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/core/urlresolvers.py", line 297, in _resolve_special
    raise ViewDoesNotExist("Tried %s. Error was: %s" % (callback, str(e)))
ViewDoesNotExist: Tried nerdfiles_net_dev.views.error_404. Error was: No module named nerdfiles_net_dev.views
2011-11-17 01:54:16,906 [WARNING] django.request: Not Found: /
2011-11-17 01:54:16,906 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/core/handlers/base.py", line 149, in get_response
    callback, param_dict = resolver.resolve404()
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/core/urlresolvers.py", line 300, in resolve404
    return self._resolve_special('404')
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/core/urlresolvers.py", line 297, in _resolve_special
    raise ViewDoesNotExist("Tried %s. Error was: %s" % (callback, str(e)))
ViewDoesNotExist: Tried nerdfiles_net_dev.views.error_404. Error was: No module named nerdfiles_net_dev.views
2011-11-17 01:54:17,484 [WARNING] django.request: Not Found: /favicon.ico/
2011-11-17 01:54:17,484 [ERROR] django.request: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/core/handlers/base.py", line 149, in get_response
    callback, param_dict = resolver.resolve404()
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/core/urlresolvers.py", line 300, in resolve404
    return self._resolve_special('404')
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/core/urlresolvers.py", line 297, in _resolve_special
    raise ViewDoesNotExist("Tried %s. Error was: %s" % (callback, str(e)))
ViewDoesNotExist: Tried nerdfiles_net_dev.views.error_404. Error was: No module named nerdfiles_net_dev.views
2011-11-17 01:55:48,569 [WARNING] django.request: Not Found: /playground/js-loader-comparison/1_labjs.html/
2011-11-17 01:55:48,570 [ERROR] django.request: Internal Server Error: /playground/js-loader-comparison/1_labjs.html/
Traceback (most recent call last):
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/core/handlers/base.py", line 149, in get_response
    callback, param_dict = resolver.resolve404()
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/core/urlresolvers.py", line 300, in resolve404
    return self._resolve_special('404')
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/core/urlresolvers.py", line 297, in _resolve_special
    raise ViewDoesNotExist("Tried %s. Error was: %s" % (callback, str(e)))
ViewDoesNotExist: Tried nerdfiles_net_dev.views.error_404. Error was: No module named nerdfiles_net_dev.views
2011-11-17 01:58:16,547 [WARNING] django.request: Not Found: /
2011-11-17 01:58:16,548 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/core/handlers/base.py", line 149, in get_response
    callback, param_dict = resolver.resolve404()
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/core/urlresolvers.py", line 300, in resolve404
    return self._resolve_special('404')
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/core/urlresolvers.py", line 297, in _resolve_special
    raise ViewDoesNotExist("Tried %s. Error was: %s" % (callback, str(e)))
ViewDoesNotExist: Tried views.error_404. Error was: No module named view_utils
2011-11-17 01:58:19,593 [WARNING] django.request: Not Found: /
2011-11-17 01:58:19,594 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/core/handlers/base.py", line 149, in get_response
    callback, param_dict = resolver.resolve404()
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/core/urlresolvers.py", line 300, in resolve404
    return self._resolve_special('404')
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/core/urlresolvers.py", line 297, in _resolve_special
    raise ViewDoesNotExist("Tried %s. Error was: %s" % (callback, str(e)))
ViewDoesNotExist: Tried views.error_404. Error was: No module named view_utils
2011-11-17 01:58:20,316 [WARNING] django.request: Not Found: /favicon.ico/
2011-11-17 01:58:20,316 [ERROR] django.request: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/core/handlers/base.py", line 149, in get_response
    callback, param_dict = resolver.resolve404()
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/core/urlresolvers.py", line 300, in resolve404
    return self._resolve_special('404')
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/core/urlresolvers.py", line 297, in _resolve_special
    raise ViewDoesNotExist("Tried %s. Error was: %s" % (callback, str(e)))
ViewDoesNotExist: Tried views.error_404. Error was: No module named view_utils
2011-11-17 01:59:55,367 [WARNING] django.request: Not Found: /
2011-11-17 01:59:55,369 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/core/handlers/base.py", line 150, in get_response
    response = callback(request, **param_dict)
  File "/home/nerdfiles/webapps/django/nerdfiles_net/views.py", line 31, in error_404
    return render_response('404.tmpl')
  File "/home/nerdfiles/webapps/django/nerdfiles_net/views.py", line 27, in render_response
    kwargs['context_instance'] = RequestContext(req)
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/template/context.py", line 173, in __init__
    self.update(processor(request))
  File "/home/nerdfiles/webapps/django/nerdfiles_net/context_processors.py", line 12, in site_info
    'SITE_URL': 'http://'+request.META.get('HTTP_HOST', ""),
AttributeError: 'str' object has no attribute 'META'
2011-11-17 02:10:55,592 [WARNING] django.request: Not Found: /playground/js-loader-comparison/1_labjs.html/
2011-11-17 02:10:55,594 [ERROR] django.request: Internal Server Error: /playground/js-loader-comparison/1_labjs.html/
Traceback (most recent call last):
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/core/handlers/base.py", line 150, in get_response
    response = callback(request, **param_dict)
  File "/home/nerdfiles/webapps/django/nerdfiles_net/views.py", line 31, in error_404
    return render_response('404.tmpl')
  File "/home/nerdfiles/webapps/django/nerdfiles_net/views.py", line 27, in render_response
    kwargs['context_instance'] = RequestContext(req)
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/template/context.py", line 173, in __init__
    self.update(processor(request))
  File "/home/nerdfiles/webapps/django/nerdfiles_net/context_processors.py", line 12, in site_info
    'SITE_URL': 'http://'+request.META.get('HTTP_HOST', ""),
AttributeError: 'str' object has no attribute 'META'
2011-11-17 02:14:38,503 [WARNING] django.request: Not Found: /
2011-11-17 02:14:38,504 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/core/handlers/base.py", line 150, in get_response
    response = callback(request, **param_dict)
  File "/home/nerdfiles/webapps/django/nerdfiles_net/views.py", line 31, in error_404
    return render_response('404.tmpl')
  File "/home/nerdfiles/webapps/django/nerdfiles_net/views.py", line 27, in render_response
    kwargs['context_instance'] = RequestContext(request)
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/template/context.py", line 173, in __init__
    self.update(processor(request))
  File "/home/nerdfiles/webapps/django/nerdfiles_net/context_processors.py", line 12, in site_info
    'SITE_URL': 'http://'+request.META.get('HTTP_HOST', ""),
AttributeError: 'str' object has no attribute 'META'
2011-11-17 02:14:40,271 [WARNING] django.request: Not Found: /favicon.ico/
2011-11-17 02:14:40,272 [ERROR] django.request: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/core/handlers/base.py", line 150, in get_response
    response = callback(request, **param_dict)
  File "/home/nerdfiles/webapps/django/nerdfiles_net/views.py", line 31, in error_404
    return render_response('404.tmpl')
  File "/home/nerdfiles/webapps/django/nerdfiles_net/views.py", line 27, in render_response
    kwargs['context_instance'] = RequestContext(request)
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/template/context.py", line 173, in __init__
    self.update(processor(request))
  File "/home/nerdfiles/webapps/django/nerdfiles_net/context_processors.py", line 12, in site_info
    'SITE_URL': 'http://'+request.META.get('HTTP_HOST', ""),
AttributeError: 'str' object has no attribute 'META'
2011-11-17 02:14:43,462 [WARNING] django.request: Not Found: /favicon.ico/
2011-11-17 02:14:43,464 [ERROR] django.request: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/core/handlers/base.py", line 150, in get_response
    response = callback(request, **param_dict)
  File "/home/nerdfiles/webapps/django/nerdfiles_net/views.py", line 31, in error_404
    return render_response('404.tmpl')
  File "/home/nerdfiles/webapps/django/nerdfiles_net/views.py", line 27, in render_response
    kwargs['context_instance'] = RequestContext(request)
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/template/context.py", line 173, in __init__
    self.update(processor(request))
  File "/home/nerdfiles/webapps/django/nerdfiles_net/context_processors.py", line 12, in site_info
    'SITE_URL': 'http://'+request.META.get('HTTP_HOST', ""),
AttributeError: 'str' object has no attribute 'META'
2011-11-17 02:14:44,815 [WARNING] django.request: Not Found: /favicon.ico/
2011-11-17 02:14:44,816 [ERROR] django.request: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/core/handlers/base.py", line 150, in get_response
    response = callback(request, **param_dict)
  File "/home/nerdfiles/webapps/django/nerdfiles_net/views.py", line 31, in error_404
    return render_response('404.tmpl')
  File "/home/nerdfiles/webapps/django/nerdfiles_net/views.py", line 27, in render_response
    kwargs['context_instance'] = RequestContext(request)
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/template/context.py", line 173, in __init__
    self.update(processor(request))
  File "/home/nerdfiles/webapps/django/nerdfiles_net/context_processors.py", line 12, in site_info
    'SITE_URL': 'http://'+request.META.get('HTTP_HOST', ""),
AttributeError: 'str' object has no attribute 'META'
2011-11-17 02:14:50,860 [WARNING] django.request: Not Found: /favicon.ico/
2011-11-17 02:14:50,861 [ERROR] django.request: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/core/handlers/base.py", line 150, in get_response
    response = callback(request, **param_dict)
  File "/home/nerdfiles/webapps/django/nerdfiles_net/views.py", line 31, in error_404
    return render_response('404.tmpl')
  File "/home/nerdfiles/webapps/django/nerdfiles_net/views.py", line 27, in render_response
    kwargs['context_instance'] = RequestContext(request)
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/template/context.py", line 173, in __init__
    self.update(processor(request))
  File "/home/nerdfiles/webapps/django/nerdfiles_net/context_processors.py", line 12, in site_info
    'SITE_URL': 'http://'+request.META.get('HTTP_HOST', ""),
AttributeError: 'str' object has no attribute 'META'
2011-11-17 02:14:54,589 [WARNING] django.request: Not Found: /favicon.ico/
2011-11-17 02:14:54,590 [ERROR] django.request: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/core/handlers/base.py", line 150, in get_response
    response = callback(request, **param_dict)
  File "/home/nerdfiles/webapps/django/nerdfiles_net/views.py", line 31, in error_404
    return render_response('404.tmpl')
  File "/home/nerdfiles/webapps/django/nerdfiles_net/views.py", line 27, in render_response
    kwargs['context_instance'] = RequestContext(request)
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/template/context.py", line 173, in __init__
    self.update(processor(request))
  File "/home/nerdfiles/webapps/django/nerdfiles_net/context_processors.py", line 12, in site_info
    'SITE_URL': 'http://'+request.META.get('HTTP_HOST', ""),
AttributeError: 'str' object has no attribute 'META'
2011-11-17 02:14:57,321 [WARNING] django.request: Not Found: /favicon.ico/
2011-11-17 02:14:57,322 [ERROR] django.request: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/core/handlers/base.py", line 150, in get_response
    response = callback(request, **param_dict)
  File "/home/nerdfiles/webapps/django/nerdfiles_net/views.py", line 31, in error_404
    return render_response('404.tmpl')
  File "/home/nerdfiles/webapps/django/nerdfiles_net/views.py", line 27, in render_response
    kwargs['context_instance'] = RequestContext(request)
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/template/context.py", line 173, in __init__
    self.update(processor(request))
  File "/home/nerdfiles/webapps/django/nerdfiles_net/context_processors.py", line 12, in site_info
    'SITE_URL': 'http://'+request.META.get('HTTP_HOST', ""),
AttributeError: 'str' object has no attribute 'META'
2011-11-17 02:15:21,262 [WARNING] django.request: Not Found: /favicon.ico/
2011-11-17 02:15:21,263 [ERROR] django.request: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/core/handlers/base.py", line 150, in get_response
    response = callback(request, **param_dict)
  File "/home/nerdfiles/webapps/django/nerdfiles_net/views.py", line 31, in error_404
    return render_response('404.tmpl')
  File "/home/nerdfiles/webapps/django/nerdfiles_net/views.py", line 27, in render_response
    kwargs['context_instance'] = RequestContext(request)
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/template/context.py", line 173, in __init__
    self.update(processor(request))
  File "/home/nerdfiles/webapps/django/nerdfiles_net/context_processors.py", line 12, in site_info
    'SITE_URL': 'http://'+request.META.get('HTTP_HOST', ""),
AttributeError: 'str' object has no attribute 'META'
2011-11-17 02:15:28,316 [WARNING] django.request: Not Found: /favicon.ico/
2011-11-17 02:15:28,317 [ERROR] django.request: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/core/handlers/base.py", line 150, in get_response
    response = callback(request, **param_dict)
  File "/home/nerdfiles/webapps/django/nerdfiles_net/views.py", line 31, in error_404
    return render_response('404.tmpl')
  File "/home/nerdfiles/webapps/django/nerdfiles_net/views.py", line 27, in render_response
    kwargs['context_instance'] = RequestContext(request)
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/template/context.py", line 173, in __init__
    self.update(processor(request))
  File "/home/nerdfiles/webapps/django/nerdfiles_net/context_processors.py", line 12, in site_info
    'SITE_URL': 'http://'+request.META.get('HTTP_HOST', ""),
AttributeError: 'str' object has no attribute 'META'
2011-11-17 02:15:34,292 [WARNING] django.request: Not Found: /aa/
2011-11-17 02:15:34,292 [ERROR] django.request: Internal Server Error: /aa/
Traceback (most recent call last):
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/core/handlers/base.py", line 150, in get_response
    response = callback(request, **param_dict)
  File "/home/nerdfiles/webapps/django/nerdfiles_net/views.py", line 31, in error_404
    return render_response('404.tmpl')
  File "/home/nerdfiles/webapps/django/nerdfiles_net/views.py", line 27, in render_response
    kwargs['context_instance'] = RequestContext(request)
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/template/context.py", line 173, in __init__
    self.update(processor(request))
  File "/home/nerdfiles/webapps/django/nerdfiles_net/context_processors.py", line 12, in site_info
    'SITE_URL': 'http://'+request.META.get('HTTP_HOST', ""),
AttributeError: 'str' object has no attribute 'META'
2011-11-17 02:15:34,776 [WARNING] django.request: Not Found: /favicon.ico/
2011-11-17 02:15:34,777 [ERROR] django.request: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/core/handlers/base.py", line 150, in get_response
    response = callback(request, **param_dict)
  File "/home/nerdfiles/webapps/django/nerdfiles_net/views.py", line 31, in error_404
    return render_response('404.tmpl')
  File "/home/nerdfiles/webapps/django/nerdfiles_net/views.py", line 27, in render_response
    kwargs['context_instance'] = RequestContext(request)
  File "/home/nerdfiles/webapps/django/lib/python2.7/django/template/context.py", line 173, in __init__
    self.update(processor(request))
  File "/home/nerdfiles/webapps/django/nerdfiles_net/context_processors.py", line 12, in site_info
    'SITE_URL': 'http://'+request.META.get('HTTP_HOST', ""),
AttributeError: 'str' object has no attribute 'META'
