2011-11-16 22:40:08,029 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:40:10,897 [ERROR] django.request: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:45:02,259 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:45:03,143 [ERROR] django.request: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:45:04,079 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:45:04,515 [ERROR] django.request: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:46:16,605 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:46:18,380 [ERROR] django.request: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:47:12,495 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:47:13,899 [ERROR] django.request: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:47:20,680 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:47:21,504 [ERROR] django.request: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:47:22,112 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:47:22,732 [ERROR] django.request: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:47:23,279 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:47:23,902 [ERROR] django.request: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:48:11,778 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:48:12,456 [ERROR] django.request: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:48:49,138 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:48:49,831 [ERROR] django.request: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:49:29,702 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:49:31,143 [ERROR] django.request: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:49:59,752 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:50:00,396 [ERROR] django.request: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:50:05,319 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:50:06,138 [ERROR] django.request: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:51:08,261 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:51:09,076 [ERROR] django.request: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:51:49,472 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:51:50,103 [ERROR] django.request: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:52:07,693 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:52:08,263 [ERROR] django.request: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:52:21,065 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:52:21,670 [ERROR] django.request: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:52:22,847 [ERROR] django.request: Internal Server Error: /
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 22:52:23,398 [ERROR] django.request: Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 99, in process_request
    language = self.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/cms/middleware/multilingual.py", line 83, in get_language_from_request
    lang = translation.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 124, in get_language_from_request
    return _trans.get_language_from_request(request)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 372, in get_language_from_request
    lang_code = request.session.get('django_language', None)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in get
    return self._session.get(key, default)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 195, in _get_session
    self._session_cache = self.load()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py", line 20, in load
    expire_date__gt=datetime.datetime.now()
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/manager.py", line 132, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 344, in get
    num = len(clone)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 82, in __len__
    self._result_cache = list(self.iterator())
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nerdfiles/.virtualenvs/django_nerdfiles_net_dev/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: django_session
2011-11-16 23:08:14,079 [WARNING] django.request: Not Found: /favicon.ico/
2011-11-16 23:08:58,009 [WARNING] django.request: Not Found: /favicon.ico/
2011-11-16 23:10:27,539 [WARNING] django.request: Not Found: /favicon.ico/
2011-11-16 23:10:39,915 [WARNING] django.request: Not Found: /favicon.ico/
2011-11-16 23:14:24,420 [WARNING] django.request: Not Found: /favicon.ico/
2011-11-16 23:14:28,665 [WARNING] django.request: Not Found: /favicon.ico/
2011-11-16 23:14:32,968 [WARNING] django.request: Not Found: /favicon.ico/
2011-11-16 23:14:51,802 [WARNING] django.request: Not Found: /favicon.ico/
2011-11-16 23:16:13,362 [WARNING] django.request: Not Found: /favicon.ico/
2011-11-16 23:16:18,717 [WARNING] django.request: Not Found: /favicon.ico/
2011-11-16 23:16:48,884 [WARNING] django.request: Not Found: /favicon.ico/
2011-11-16 23:16:52,606 [WARNING] django.request: Not Found: /favicon.ico/
2011-11-16 23:16:54,785 [WARNING] django.request: Not Found: /favicon.ico/
